// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kkplhcvpynxtikxzslhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrcGxoY3ZweW54dGlreHpzbGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjgzMDIsImV4cCI6MjA3MDg0NDMwMn0.4HdNDdiLhKe6lXr2uR4tIcGoiOsJbuWK1RsvxoJ_4Ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);